name: Lint and test

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make deps
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
