name: Lint, test and upload coverage to Codecov

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make deps
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Generate coverage report
      run: |
        make coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@master
